spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  hibernate:
    dialect: org.hibernate.dialect.HSQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true